name: Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build images to test
      run: |
        docker build -t danielvdm/client-test -f ./client/Dockerfile.dev ./client
        docker build -t danielvdm/api-test -f ./client/Dockerfile.dev ./api

    - name: Test all images with tests
      run: |
        docker run -e CI=true danielvdm/client-test npm test
        docker run -e CI=true danielvdm/api-test npm test

    - name: Build images
      run: |
        docker build -t danielvdm/multi-client ./client
        docker build -t danielvdm/multi-nginx ./nginx
        docker build -t danielvdm/multi-api ./api
        docker build -t danielvdm/multi-worker ./worker

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push images
      run: |
        docker push danielvdm/multi-client
        docker push danielvdm/multi-nginx
        docker push danielvdm/multi-api
        docker push danielvdm/multi-worker